"use server";

import { revalidatePath } from "next/cache";

import { redirect } from "next/navigation";

import { createClient } from "@/lib/supabase/server";

import { requireAdmin } from "@/lib/auth/require-admin";

import { projectSchema } from "@/lib/validations/project";

import {
    getProjectMediaPathFromUrl,
    PROJECT_MEDIA_BUCKET,
} from "@/lib/storage/project-media";

export type ProjectActionState = {
    message?: string;

    errors?: Partial<
        Record<
            | "title"
            | "slug"
            | "thumbnail"
            | "shortDescription"
            | "description"
            | "category"
            | "technologies"
            | "role"
            | "duration"
            | "status"
            | "problem"
            | "solution"
            | "features"
            | "challenges"
            | "outcome"
            | "gallery"
            | "githubUrl"
            | "liveUrl"
            | "order"
            | "featured"
            | "published",
            string[]
        >
    >;
};

type DeleteProjectResult = {
    success: boolean;

    error?: string;
};

function validateProject(formData: FormData) {
    return projectSchema.safeParse({
        title: formData.get("title"),

        slug: formData.get("slug"),

        thumbnail: formData.get("thumbnail"),

        shortDescription: formData.get("shortDescription"),

        description: formData.get("description"),

        category: formData.get("category"),

        technologies: formData.get("technologies"),

        role: formData.get("role") ?? "",

        duration: formData.get("duration") ?? "",

        status: formData.get("status") ?? "",

        problem: formData.get("problem") ?? "",

        solution: formData.get("solution") ?? "",

        features: formData.get("features") ?? "[]",

        challenges: formData.get("challenges") ?? "[]",

        outcome: formData.get("outcome") ?? "",

        gallery: formData.get("gallery") ?? "[]",

        githubUrl: formData.get("githubUrl") ?? "",

        liveUrl: formData.get("liveUrl") ?? "",

        order: formData.get("order"),

        featured: formData.get("featured"),

        published: formData.get("published"),
    });
}

function revalidateProjectPages(slug?: string) {
    revalidatePath("/");

    revalidatePath("/projects");

    revalidatePath("/admin/projects");

    if (slug) {
        revalidatePath(`/projects/${slug}`);
    }
}

type ServerSupabaseClient = Awaited<ReturnType<typeof createClient>>;

const STALE_PROJECT_MEDIA_AGE_MS = 72 * 60 * 60 * 1000;

const PROJECT_MEDIA_LIST_PAGE_SIZE = 100;

const PROJECT_MEDIA_REMOVE_BATCH_SIZE = 100;

const managedProjectMediaFilePattern =
    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(?:jpg|jpeg|png|webp)$/i;

async function findStaleProjectMediaPaths(
    supabase: ServerSupabaseClient,
    folder: "thumbnails" | "gallery",
    referencedPaths: Set<string>,
): Promise<string[]> {
    const stalePaths: string[] = [];

    const cutoff = Date.now() - STALE_PROJECT_MEDIA_AGE_MS;

    let offset = 0;

    while (true) {
        const { data, error } = await supabase.storage
            .from(PROJECT_MEDIA_BUCKET)
            .list(`projects/${folder}`, {
                limit: PROJECT_MEDIA_LIST_PAGE_SIZE,
                offset,
                sortBy: {
                    column: "name",
                    order: "asc",
                },
            });

        if (error) {
            console.warn(`Unable to inspect stale project ${folder}:`, error);

            return stalePaths;
        }

        const items = data ?? [];

        for (const item of items) {
            /*
             * Folder entries do not represent files.
             * Supabase returns null file metadata for folders.
             */

            if (!item.id || !item.created_at) {
                continue;
            }

            /*
             * Only manage files generated by our project
             * uploader. Custom/manual files are ignored.
             */

            if (!managedProjectMediaFilePattern.test(item.name)) {
                continue;
            }

            const createdAt = new Date(item.created_at).getTime();

            if (Number.isNaN(createdAt)) {
                continue;
            }

            if (createdAt > cutoff) {
                continue;
            }

            const path = `projects/${folder}/${item.name}`;

            /*
             * Never delete an object still referenced
             * by any project row.
             */

            if (referencedPaths.has(path)) {
                continue;
            }

            stalePaths.push(path);
        }

        if (items.length < PROJECT_MEDIA_LIST_PAGE_SIZE) {
            break;
        }

        offset += PROJECT_MEDIA_LIST_PAGE_SIZE;
    }

    return stalePaths;
}

async function cleanupStaleProjectMediaBestEffort(
    supabase: ServerSupabaseClient,
) {
    /*
     * Read every project media reference first.
     * This protects media that is still in use.
     */

    const { data: projects, error: projectsError } = await supabase
        .from("projects")
        .select(
            `
                thumbnail_url,
                gallery
            `,
        );

    if (projectsError) {
        console.warn(
            "Unable to read project media references for stale cleanup:",
            projectsError,
        );

        return;
    }

    const referencedPaths = new Set<string>();

    for (const projectRow of projects ?? []) {
        if (typeof projectRow.thumbnail_url === "string") {
            const thumbnailPath = getProjectMediaPathFromUrl(
                projectRow.thumbnail_url,
            );

            if (thumbnailPath) {
                referencedPaths.add(thumbnailPath);
            }
        }

        const gallery = Array.isArray(projectRow.gallery)
            ? projectRow.gallery
            : [];

        gallery.forEach((item: { image?: unknown }) => {
            if (typeof item.image !== "string") {
                return;
            }

            const path = getProjectMediaPathFromUrl(item.image);

            if (path) {
                referencedPaths.add(path);
            }
        });
    }

    /*
     * Look only inside the two project media
     * folders managed by ProjectImageUploader.
     */

    const [staleThumbnails, staleGallery] = await Promise.all([
        findStaleProjectMediaPaths(supabase, "thumbnails", referencedPaths),

        findStaleProjectMediaPaths(supabase, "gallery", referencedPaths),
    ]);

    const stalePaths = Array.from(
        new Set([...staleThumbnails, ...staleGallery]),
    );

    if (stalePaths.length === 0) {
        return;
    }

    /*
     * Remove stale objects in small batches.
     * Cleanup is best-effort and must never
     * make a successful project CRUD action fail.
     */

    for (
        let index = 0;
        index < stalePaths.length;
        index += PROJECT_MEDIA_REMOVE_BATCH_SIZE
    ) {
        const batch = stalePaths.slice(
            index,
            index + PROJECT_MEDIA_REMOVE_BATCH_SIZE,
        );

        const { error } = await supabase.storage
            .from(PROJECT_MEDIA_BUCKET)
            .remove(batch);

        if (error) {
            console.warn("Unable to remove stale project media:", error);
        }
    }
}

/*
 * CREATE
 */

export async function createProject(
    _previousState: ProjectActionState,

    formData: FormData,
): Promise<ProjectActionState> {
    await requireAdmin();

    const validated = validateProject(formData);

    if (!validated.success) {
        return {
            message: "Please correct the form errors.",

            errors: validated.error.flatten().fieldErrors,
        };
    }

    const project = validated.data;

    const supabase = await createClient();

    const { error } = await supabase.from("projects").insert({
        title: project.title,

        slug: project.slug,

        thumbnail_url: project.thumbnail,

        short_description: project.shortDescription,

        description: project.description,

        category: project.category,

        technologies: project.technologies,

        role: project.role || null,

        duration: project.duration || null,

        status: project.status || null,

        problem: project.problem || null,

        solution: project.solution || null,

        features: project.features,

        challenges: project.challenges,

        outcome: project.outcome || null,

        gallery: project.gallery,

        github_url: project.githubUrl || null,

        live_url: project.liveUrl || null,

        featured: project.featured,

        published: project.published,

        sort_order: project.order,
    });

    if (error) {
        if (error.code === "23505") {
            return {
                message: "A project with this slug already exists.",
            };
        }

        console.error("Create project error:", error);

        return {
            message: "Unable to create the project.",
        };
    }

    await cleanupStaleProjectMediaBestEffort(supabase);

    revalidateProjectPages(project.slug);

    redirect("/admin/projects");
}

/*
 * UPDATE
 */

export async function updateProject(
    id: string,

    _previousState: ProjectActionState,

    formData: FormData,
): Promise<ProjectActionState> {
    await requireAdmin();

    const validated = validateProject(formData);

    if (!validated.success) {
        return {
            message: "Please correct the form errors.",

            errors: validated.error.flatten().fieldErrors,
        };
    }

    const project = validated.data;

    const supabase = await createClient();

    /*
     * Read the current project before updating.
     *
     * We need the old slug for route revalidation
     * and the old media references so unused
     * Supabase Storage files can be cleaned up
     * only after the database update succeeds.
     */

    const { data: existingProject, error: existingProjectError } =
        await supabase
            .from("projects")
            .select(
                `
                slug,
                thumbnail_url,
                gallery
            `,
            )
            .eq("id", id)
            .maybeSingle();

    if (existingProjectError) {
        console.error(
            "Read existing project before update error:",
            existingProjectError,
        );

        return {
            message: "Unable to load the existing project before updating.",
        };
    }

    if (!existingProject) {
        return {
            message: "The project could not be found.",
        };
    }

    /*
     * Update database first.
     *
     * No old media is deleted before this succeeds.
     */

    const { error } = await supabase
        .from("projects")
        .update({
            title: project.title,

            slug: project.slug,

            thumbnail_url: project.thumbnail,

            short_description: project.shortDescription,

            description: project.description,

            category: project.category,

            technologies: project.technologies,

            role: project.role || null,

            duration: project.duration || null,

            status: project.status || null,

            problem: project.problem || null,

            solution: project.solution || null,

            features: project.features,

            challenges: project.challenges,

            outcome: project.outcome || null,

            gallery: project.gallery,

            github_url: project.githubUrl || null,

            live_url: project.liveUrl || null,

            featured: project.featured,

            published: project.published,

            sort_order: project.order,

            updated_at: new Date().toISOString(),
        })
        .eq("id", id);

    if (error) {
        if (error.code === "23505") {
            return {
                message: "A project with this slug already exists.",
            };
        }

        console.error("Update project error:", error);

        return {
            message: "Unable to update the project.",
        };
    }

    /*
     * =============================================
     * SAFE MEDIA CLEANUP
     * =============================================
     *
     * The database update has succeeded.
     *
     * Now compare:
     *
     * OLD MEDIA
     * vs
     * NEW MEDIA
     *
     * Only files no longer referenced by the
     * updated project will be removed.
     */

    const oldMediaPaths = new Set<string>();

    const newMediaPaths = new Set<string>();

    /*
     * Previous thumbnail
     */

    const oldThumbnailPath = getProjectMediaPathFromUrl(
        existingProject.thumbnail_url ?? "",
    );

    if (oldThumbnailPath) {
        oldMediaPaths.add(oldThumbnailPath);
    }

    /*
     * Previous gallery
     */

    const oldGallery = Array.isArray(existingProject.gallery)
        ? (existingProject.gallery as Array<{
              image?: string;
          }>)
        : [];

    oldGallery.forEach((item) => {
        if (!item.image) {
            return;
        }

        const path = getProjectMediaPathFromUrl(item.image);

        if (path) {
            oldMediaPaths.add(path);
        }
    });

    /*
     * New thumbnail
     */

    const newThumbnailPath = getProjectMediaPathFromUrl(project.thumbnail);

    if (newThumbnailPath) {
        newMediaPaths.add(newThumbnailPath);
    }

    /*
     * New gallery
     */

    project.gallery.forEach((item) => {
        const path = getProjectMediaPathFromUrl(item.image);

        if (path) {
            newMediaPaths.add(path);
        }
    });

    /*
     * Delete only media that existed before
     * but is no longer referenced anywhere
     * in the updated project.
     */

    const pathsToRemove = Array.from(oldMediaPaths).filter(
        (path) => !newMediaPaths.has(path),
    );

    if (pathsToRemove.length > 0) {
        const { error: storageError } = await supabase.storage
            .from(PROJECT_MEDIA_BUCKET)
            .remove(pathsToRemove);

        if (storageError) {
            /*
             * Database update already succeeded,
             * so a cleanup failure must not
             * roll back or break the project.
             *
             * The old file can be cleaned up
             * manually later if necessary.
             */

            console.warn(
                "Project updated but old media cleanup failed:",
                storageError,
            );
        }
    }

    /*
     * Clean up any abandoned project uploads
     * older than 72 hours. This runs only after
     * the project update and normal old-media
     * cleanup have completed successfully.
     */

    await cleanupStaleProjectMediaBestEffort(supabase);

    /*
     * Revalidate old slug in case the slug changed.
     */

    if (existingProject.slug) {
        revalidateProjectPages(existingProject.slug);
    }

    /*
     * Revalidate the new/current project routes.
     */

    revalidateProjectPages(project.slug);

    redirect("/admin/projects");
}

/*
 * DELETE
 */

export async function deleteProject(id: string): Promise<DeleteProjectResult> {
    await requireAdmin();

    const supabase = await createClient();

    /*
     * Read project assets before
     * deleting the database row.
     */

    const { data: existingProject, error: readError } = await supabase
        .from("projects")
        .select(
            `
                slug,
                thumbnail_url,
                gallery
                `,
        )
        .eq("id", id)
        .maybeSingle();

    if (readError) {
        return {
            success: false,

            error: "Unable to read the project before deletion.",
        };
    }

    const { error: deleteError } = await supabase
        .from("projects")
        .delete()
        .eq("id", id);

    if (deleteError) {
        console.error(deleteError);

        return {
            success: false,

            error: "Unable to delete the project.",
        };
    }

    /*
     * Best-effort media cleanup.
     */

    if (existingProject) {
        const paths: string[] = [];

        const thumbnailPath = getProjectMediaPathFromUrl(
            existingProject.thumbnail_url ?? "",
        );

        if (thumbnailPath) {
            paths.push(thumbnailPath);
        }

        const gallery = Array.isArray(existingProject.gallery)
            ? existingProject.gallery
            : [];

        gallery.forEach((item: { image?: string }) => {
            if (!item.image) {
                return;
            }

            const path = getProjectMediaPathFromUrl(item.image);

            if (path) {
                paths.push(path);
            }
        });

        if (paths.length > 0) {
            const { error: storageError } = await supabase.storage
                .from(PROJECT_MEDIA_BUCKET)
                .remove(paths);

            if (storageError) {
                console.warn(
                    "Project deleted but media cleanup failed:",
                    storageError,
                );
            }
        }

        revalidateProjectPages(existingProject.slug);
    } else {
        revalidateProjectPages();
    }

    await cleanupStaleProjectMediaBestEffort(supabase);

    return {
        success: true,
    };
}

/*
 * PUBLISH
 */

export async function setProjectPublished(
    id: string,

    published: boolean,
) {
    await requireAdmin();

    const supabase = await createClient();

    const { data, error } = await supabase
        .from("projects")
        .update({
            published,

            updated_at: new Date().toISOString(),
        })
        .eq("id", id)
        .select("slug")
        .maybeSingle();

    if (error) {
        throw new Error("Unable to update project publish status.");
    }

    revalidateProjectPages(data?.slug);
}

/*
 * FEATURE
 */

export async function setProjectFeatured(
    id: string,

    featured: boolean,
) {
    await requireAdmin();

    const supabase = await createClient();

    const { data, error } = await supabase
        .from("projects")
        .update({
            featured,

            updated_at: new Date().toISOString(),
        })
        .eq("id", id)
        .select("slug")
        .maybeSingle();

    if (error) {
        throw new Error("Unable to update featured status.");
    }

    revalidateProjectPages(data?.slug);
}
